import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr';

export const translations = {
  en: {
    home: 'Home',
    reports: 'Reports',
    community: 'Community Feed',
    profile: 'Profile',
    dashboard: 'Dashboard',
    geospatial: 'Geospatial',
    insights: 'AI Insights',
    audit: 'Audit Log',
    tagline: 'AI-Powered Constituency Intelligence Platform',
    citizen_login: 'Citizen Login',
    admin_login: 'Admin Login',
    citizen_portal_btn: 'Citizen Portal ▷',
    admin_center_btn: 'Admin Center 🛡️',
    capabilities_title: 'The Intelligence Layer for Your Constituency',
    capabilities_desc: 'Utilizing state-of-the-art AI to transform raw local feedback into actionable development insights.',
    share_concern: 'Share Your Concern',
    state: 'State',
    district: 'District',
    city: 'City',
    ward_label: 'Ward / Area Name',
    category: 'Category',
    specify_other: 'Specify Other Category',
    desc_label: 'Detailed Description',
    voice_typing: 'Voice Typing',
    listening: 'Listening...',
    upload_proof: 'Upload Photo / Video Proof',
    upload_hint: '(Submitting media proof ensures high-priority processing)',
    submit_report: 'Submit Report / 𝍢𝍢𝍢𝍢𝍢',
    submitting: 'Registering Complaint...',
    call_hotline: 'Call voice hotline: 1800-JAN-SAATH',
    whatsapp_hotline: 'WhatsApp complaint: +91 98000 00000',
    submitted: 'Complaint Submitted Successfully!',
    submitted_desc: 'Your concern has been registered. The intelligence engine is routing verification checks.',
    triage_profile: 'Triage Profile:',
    severity: 'Severity',
    priority_score: 'Priority Score',
    file_another: 'File Another Report',
    community_feed: 'Community Feed',
    feed_description: 'Live complaints from your constituency - highest priority first',
    upvotes: 'Upvotes',
    comments: 'Comments',
    abort: 'Abort',
    aborted_notice: 'This incident report has been aborted/withdrawn by the citizen.',
    anonymous: 'Anonymous Citizen',
    add_comment: 'Add your comment...',
    active_hotspots: 'Geospatial Active Hotspots',
    map_desc: 'Click pins to view the local issues mapping index verified by geo intelligence node.',
    agent_workflow: 'Computational Agent Graph Workflow',
    incidents_directory: 'Ward Infrastructure Incidents Directory',
    id: 'ID',
    status: 'Status',
    logged_at: 'Logged At',
    profile_rep: 'Citizen Representative',
    email_addr: 'Email Address',
    phone_num: 'Phone Number',
    age: 'Age',
    years: 'Years',
    default_ward: 'Default Ward',
    city_district: 'City & District',
    state_region: 'State Region',
    total_issues: 'Total Issues',
    resolved: 'Resolved',
    avg_resolution: 'Avg Resolution',
    satisfaction: 'Satisfaction',
    draft_proposal: 'DRAFT OFFICIAL PROPOSAL',
    command_insight: 'AI Command Insight',
    urgency_score: 'Urgency Score',
    affected_pop: 'Affected Population',
    fiscal_estimate: 'Fiscal Estimate',
    generate_proposal: 'Generate Official Proposal',
    proposal_success: 'Proposal drafted in Google Docs! Launched in tab.',
    empty_column: 'Empty Column',
    logout: 'Logout',
    call_us: '📞 Call Us',
    call_description: 'Speak your complaint - no internet needed',
    whatsapp: '💬 WhatsApp',
    whatsapp_description: 'Send message on WhatsApp',
    upload_photo: '📷 Upload Photo',
    photo_description: 'Take photo of the problem',
    text_complaint: '✍️ Text Complaint',
    text_description: 'Type your complaint',
    submit: 'Submit',
    done: 'Done',
    describe_problem: 'Describe your problem in detail...',
    enter_ward: 'Enter ward name (e.g., Chinhat)',
    photo_hint: 'Take a clear photo of the infrastructure issue',
    no_complaints: 'No complaints yet. Be the first to report!',
    loading: 'Loading',
    priority: 'Priority',
    merged_issue: 'Merged Issue',
    days: 'days',
    summary: 'Summary',
    workflow_title: 'Workflow Action Control',
    pass_review: '🔍 Pass for Review',
    allocate_funds: '💰 Allocate Funds',
    resolve_direct: '✅ Resolve Direct',
    resolve_issue: '✅ Resolve Issue',
    resolved_closed: '🎉 Issue is fully resolved & closed.',
    open_google_doc: '🔗 Open Google Doc Draft',
    admin_feed: 'Admin Feed',
    post_update: 'Post Progress Update',
    update_msg: 'Update Message',
    category_label: 'Category',
    update_type: 'Update Type',
    ward_optional: 'Ward / Area (Optional)',
    publish_update: '📢 Publish Progress Update',
    live_feed: 'Live Updates Feed',
    no_updates: 'No updates from the administrator yet.',
    official_tag: 'Official',
    admin_updates: 'Admin Updates',
      cap_voice_title: 'Voice-First Intake',
    cap_voice_desc: 'Removing literacy barriers by transcribing local dialects and speech instantly via multilingual AI, ensuring every voice is captured accurately.',
    cap_voice_link: 'Learn More →',
    cap_geo_title: 'Geospatial Verification',
    cap_geo_desc: 'Mapping regional needs using precision satellite and open-source data to verify development milestones and infrastructure requirements.',
    cap_geo_link: 'View Map Demo →',
    cap_pred_title: 'Predictive Governance',
    cap_pred_desc: 'Forecasting future infrastructure needs and resource allocation automatically using deep-learning models trained on community feedback.',
    cap_pred_link: 'Explore AI Insights →',
},
  hi: {
    home: 'होम',
    reports: 'रिपोर्ट',
    community: 'कम्युनिटी फीड',
    profile: 'प्रोफाइल',
    dashboard: 'डैशबोर्ड',
    geospatial: 'जियोस्पेशियल',
    insights: 'एआई अंतर्दृष्टि',
    audit: 'ऑडिट लॉग',
    tagline: 'एआई-संचालित निर्वाचन क्षेत्र बुद्धिमत्ता मंच',
    citizen_login: 'नागरिक लॉगिन',
    admin_login: 'एडमिन लॉगिन',
    citizen_portal_btn: 'नागरिक पोर्टल ▷',
    admin_center_btn: 'एडमिन केंद्र 🛡️',
    capabilities_title: 'आपके निर्वाचन क्षेत्र के लिए इंटेलिजेंस लेयर',
    capabilities_desc: 'सटीक सामुदायिक प्रतिक्रिया को व्यावहारिक विकास अंतर्दृष्टि में बदलने के लिए अत्याधुनिक एआई का उपयोग करना।',
    share_concern: 'अपनी चिंता साझा करें',
    state: 'राज्य',
    district: 'जिला',
    city: 'शहर',
    ward_label: 'वार्ड / क्षेत्र का नाम',
    category: 'श्रेणी',
    specify_other: 'अन्य श्रेणी निर्दिष्ट करें',
    desc_label: 'विस्तृत विवरण',
    voice_typing: 'आवाज से टाइप करें',
    listening: 'सुन रहा है...',
    upload_proof: 'फोटो / वीडियो प्रमाण अपलोड करें',
    upload_hint: '(मीडिया प्रमाण जमा करने से उच्च प्राथमिकता सुनिश्चित होती है)',
    submit_report: 'रिपोर्ट जमा करें / 𝍢𝍢𝍢𝍢𝍢',
    submitting: 'शिकायत दर्ज हो रही है...',
    call_hotline: 'कॉल वॉइस हॉटलाइन: 1800-JAN-SAATH',
    whatsapp_hotline: 'व्हाट्सएप शिकायत: +91 98000 00000',
    submitted: 'शिकायत सफलतापूर्वक दर्ज की गई!',
    submitted_desc: 'आपकी शिकायत दर्ज कर ली गई है। इंटेलिजेंस इंजन सत्यापन की जांच कर रहा है।',
    triage_profile: 'वर्गीकरण विवरण:',
    severity: 'गंभीरता',
    priority_score: 'प्राथमिकता स्कोर',
    file_another: 'दूसरी शिकायत दर्ज करें',
    community_feed: 'कम्युनिटी फीड',
    feed_description: 'आपके निर्वाचन क्षेत्र से लाइव शिकायतें - पहले उच्चतम प्राथमिकता',
    upvotes: 'अपवोट',
    comments: 'टिप्पणियां',
    abort: 'निरस्त करें',
    aborted_notice: 'यह शिकायत नागरिक द्वारा निरस्त/वापस ले ली गई है।',
    anonymous: 'अनाम नागरिक',
    add_comment: 'अपनी टिप्पणी जोड़ें...',
    active_hotspots: 'भौगोलिक सक्रिय हॉटस्पॉट',
    map_desc: 'भौगोलिक इंटेलिजेंस नोड द्वारा सत्यापित स्थानीय मुद्दों के मानचित्र सूचकांक को देखने के लिए पिन पर क्लिक करें।',
    agent_workflow: 'कम्प्यूटेशनल एजेंट ग्राफ वर्कफ़्लो',
    incidents_directory: 'वार्ड बुनियादी ढांचा घटना निर्देशिका',
    id: 'आईडी',
    status: 'स्थिति',
    logged_at: 'दर्ज किया गया',
    profile_rep: 'नागरिक प्रतिनिधि',
    email_addr: 'ईमेल पता',
    phone_num: 'फ़ोन नंबर',
    age: 'आयु',
    years: 'वर्ष',
    default_ward: 'डिफ़ॉल्ट वार्ड',
    city_district: 'शहर और जिला',
    state_region: 'राज्य क्षेत्र',
    total_issues: 'कुल मुद्दे',
    resolved: 'निवारण हुए',
    avg_resolution: 'औसत समाधान',
    satisfaction: 'संतुष्टि',
    draft_proposal: 'आधिकारिक प्रस्ताव का मसौदा',
    command_insight: 'एआई कमांड अंतर्दृष्टि',
    urgency_score: 'अति-आवश्यकता स्कोर',
    affected_pop: 'प्रभावित जनसंख्या',
    fiscal_estimate: 'राजकोषीय अनुमान',
    generate_proposal: 'आधिकारिक प्रस्ताव उत्पन्न करें',
    proposal_success: 'गूगल डॉक्स में प्रस्ताव तैयार किया गया! नए टैब में खोला गया।',
    empty_column: 'खाली कॉलम',
    logout: 'लॉगआउट',
    call_us: '📞 कॉल करें',
    call_description: 'अपनी शिकायत बोलें - इंटरनेट की जरूरत नहीं',
    whatsapp: '💬 व्हाट्सएप',
    whatsapp_description: 'व्हाट्सएप पर संदेश भेजें',
    upload_photo: '📷 फोटो अपलोड करें',
    photo_description: 'समस्या की फोटो लें',
    text_complaint: '✍️ टेक्स्ट शिकायत',
    text_description: 'अपनी शिकायत टाइप करें',
    submit: 'जमा करें',
    done: 'हो गया',
    describe_problem: 'अपनी समस्या का विस्तार से वर्णन करें...',
    enter_ward: 'वार्ड का नाम दर्ज करें (जैसे, चिनहट)',
    photo_hint: 'समस्या की स्पष्ट फोटो लें',
    no_complaints: 'अभी कोई शिकायत नहीं। पहले रिपोर्ट करने वाले बनें!',
    loading: 'लोड हो रहा है',
    priority: 'प्राथमिकता',
    merged_issue: 'विलयित मुद्दा',
    days: 'दिन',
    summary: 'सारांश',
    workflow_title: 'कार्यप्रवाह कार्रवाई नियंत्रण',
    pass_review: '🔍 समीक्षा के लिए भेजें',
    allocate_funds: '💰 धन आवंटित करें',
    resolve_direct: '✅ सीधे समाधान करें',
    resolve_issue: '✅ समस्या का समाधान करें',
    resolved_closed: '🎉 मुद्दा पूरी तरह से हल और बंद हो गया है।',
    open_google_doc: '🔗 Google डॉक ड्राफ्ट खोलें',
    admin_feed: 'एडमिन फीड',
    post_update: 'प्रगति अपडेट पोस्ट करें',
    update_msg: 'अपडेट संदेश',
    category_label: 'श्रेणी',
    update_type: 'अपडेट प्रकार',
    ward_optional: 'वार्ड / क्षेत्र (वैकल्पिक)',
    publish_update: '📢 प्रगति अपडेट प्रकाशित करें',
    live_feed: 'लाइव अपडेट फीड',
    no_updates: 'प्रशासक की ओर से अभी तक कोई अपडेट नहीं है।',
    official_tag: 'आधिकारिक',
    admin_updates: 'एडमिन अपडेट',
      cap_voice_title: 'आवाज-प्रथम इनटेक',
    cap_voice_desc: 'बहुभाषी एआई के माध्यम से स्थानीय बोलियों और भाषणों को तुरंत ट्रांसक्राइब करके साक्षरता बाधाओं को दूर करना, यह सुनिश्चित करना कि हर आवाज सही ढंग से दर्ज हो।',
    cap_voice_link: 'और जानें →',
    cap_geo_title: 'जियोस्पेशियल सत्यापन',
    cap_geo_desc: 'विकास के मील के पत्थर और बुनियादी ढांचे की आवश्यकताओं को सत्यापित करने के लिए सटीक उपग्रह और ओपन-सोर्स डेटा का उपयोग करके क्षेत्रीय आवश्यकताओं का मानचित्रण करना।',
    cap_geo_link: 'मानचित्र डेमो देखें →',
    cap_pred_title: 'पूर्वानुमानित शासन',
    cap_pred_desc: 'सामुदायिक प्रतिक्रिया पर प्रशिक्षित डीप-लर्निंग और संसाधन आवंटन का स्वचालित रूप से पूर्वानुमान लगाना।',
    cap_pred_link: 'एआई अंतर्दृष्टि का अन्वेषण करें →',
},
  bn: {
    home: 'হোম',
    reports: 'রিপোর্ট',
    community: 'কমিউনিটি ফিড',
    profile: 'প্রোফাইল',
    dashboard: 'ড্যাশবোর্ড',
    geospatial: 'জিওস্পেশিয়াল',
    insights: 'এআই অন্তর্দৃষ্টি',
    audit: 'অডিট লগ',
    tagline: 'এআই-চালিত নির্বাচনী এলাকা ইন্টেলিজেন্স প্ল্যাটফর্ম',
    citizen_login: 'নাগরিক লগইন',
    admin_login: 'অ্যাডমিন লগইন',
    citizen_portal_btn: 'নাগরিক পোর্টাল ▷',
    admin_center_btn: 'অ্যাডমিন কেন্দ্র 🛡️',
    capabilities_title: 'আপনার নির্বাচনী এলাকার জন্য ইন্টেলিজেন্স লেয়ার',
    capabilities_desc: 'উন্নয়নমূলক প্রয়াসগুলিকে সহজ ও ত্বরান্বিত করতে কাজ করছে।',
    share_concern: 'আপনার অভিযোগ জানান',
    state: 'রাজ্য',
    district: 'জেলা',
    city: 'শহর',
    ward_label: 'ওয়ার্ড / এলাকার নাম',
    category: 'বিভাগ',
    specify_other: 'অন্যান্য বিভাগ উল্লেখ করুন',
    desc_label: 'বিস্তারিত বিবরণ',
    voice_typing: 'ভয়েস টাইপিং',
    listening: 'শুনছি...',
    upload_proof: 'ছবি / ভিডিও প্রমাণ আপলোড করুন',
    upload_hint: '(মিডিয়া প্রমাণ সহ অভিযোগ দায়ের করলে দ্রুত সমাধান করা হবে)',
    submit_report: 'অভিযোগ জমা দিন / 𝍢𝍢𝍢𝍢𝍢',
    submitting: 'অভিযোগ নথিভুক্ত হচ্ছে...',
    call_hotline: 'ভয়েস হটলাইন কল করুন: 1800-JAN-SAATH',
    whatsapp_hotline: 'হোয়াটসঅ্যাপে অভিযোগ: +91 98000 00000',
    submitted: 'অভিযোগ সফলভাবে জমা দেওয়া হয়েছে!',
    submitted_desc: 'আপনার অভিযোগ নথিভুক্ত হয়েছে। এআই ইঞ্জিন তার সত্যতা যাচাই করছে।',
    triage_profile: 'শ্রেণীবিন্যাস বিবরণ:',
    severity: 'তীব্রता',
    priority_score: 'অগ্রাধিকার স্কোর',
    file_another: 'আরেকটি অভিযোগ দায়ের করুন',
    community_feed: 'কমিউনিটি ফিড',
    feed_description: 'আপনার নির্বাচনী এলাকার লাইভ অভিযোগসমূহ - সর্বোচ্চ অগ্রাধিকার সবার আগে',
    upvotes: 'আপভোট',
    comments: 'মন্তব্য',
    abort: 'বাতিল করুন',
    aborted_notice: 'এই অভিযোগটি সংশ্লিষ্ট নাগরিক দ্বারা প্রত্যাহার বা বাতিল করা হয়েছে।',
    anonymous: 'নাম প্রকাশে অনিচ্ছুক নাগরিক',
    add_comment: 'আপনার মন্তব্য যোগ করুন...',
    active_hotspots: 'ভৌগোলিক সক্রিয় হটস্পট',
    map_desc: 'জিও-ইন্টেলিজেন্স নোড দ্বারা যাচাইকৃত স্থানীয় সমস্যাগুলির ম্যাপ দেখতে পিনগুলিতে ক্লিক করুন।',
    agent_workflow: 'কম্পিউটেশনের এজেন্ট গ্রাফ ওয়ার্কফ্লো',
    incidents_directory: 'ওয়ার্ড পরিকাঠামো ঘটনা তালিকা',
    id: 'আইডি',
    status: 'অবস্থা',
    logged_at: 'নথিভুক্তির সময়',
    profile_rep: 'নাগরিক প্রতিনিধি',
    email_addr: 'ইমেল ঠিকানা',
    phone_num: 'ফোন নম্বর',
    age: 'বয়স',
    years: 'বছর',
    default_ward: 'ডিফল্ট ওয়ার্ড',
    city_district: 'শহর ও জেলা',
    state_region: 'রাজ্য অঞ্চল',
    total_issues: 'মোট সমস্যা',
    resolved: 'মীমাংসিত',
    avg_resolution: 'গড় নিষ্পত্তি সময়',
    satisfaction: 'संतुष्टि',
    draft_proposal: 'सरकारी प्रस्तावना খসড়া',
    command_insight: 'এআই কমান্ড অন্তর্দৃষ্টি',
    urgency_score: 'জরুরি অবস্থা স্কোর',
    affected_pop: 'ক্ষতিগ্রস্ত জনসংখ্যা',
    fiscal_estimate: 'রাজস্ব প্রাক্কলন',
    generate_proposal: 'सरकारी प्रस्तावনা তৈরি করুন',
    proposal_success: 'গুগল ডক্সে প্রস্তাবনা সফলভাবে তৈরি হয়েছে! অন্য ট্যাবে খুলুন।',
    empty_column: 'ফাঁকা কলাম',
    logout: 'লগআউট',
    call_us: '📞 কল করুন',
    call_description: 'আপনার অভিযোগ বলুন - ইন্টারনেট প্রয়োজন নেই',
    whatsapp: '💬 হোয়াটসঅ্যাপ',
    whatsapp_description: 'হোয়াটসঅ্যাপে বার্তা পাঠান',
    upload_photo: '📷 ছবি আপলোড করুন',
    photo_description: 'সমস্যার ছবি তুলুন',
    text_complaint: '✍️ লিখিত অভিযোগ',
    text_description: 'আপনার অভিযোগ টাইপ করুন',
    submit: 'জমা দিন',
    done: 'সম্পন্ন',
    describe_problem: 'আপনার সমস্যা বিস্তারিত বর্ণনা করুন...',
    enter_ward: 'ওয়ার্ডের নাম লিখুন (যেমন, চিনহাট)',
    photo_hint: 'সমস্যার একটি পরিষ্কার ছবি তুলুন',
    no_complaints: 'এখনও কোনো অভিযোগ নেই। প্রথম রিপোর্ট করুন!',
    loading: 'লোড হচ্ছে',
    priority: 'অগ্রাধিকার',
    merged_issue: 'একত্রিত সমস্যা',
    days: 'দিন',
    summary: 'সারসংক্ষেপ',
      workflow_title: 'Workflow Action Control',
    pass_review: '🔍 Pass for Review',
    allocate_funds: '💰 Allocate Funds',
    resolve_direct: '✅ Resolve Direct',
    resolve_issue: '✅ Resolve Issue',
    resolved_closed: '🎉 Issue is fully resolved & closed.',
    open_google_doc: '🔗 Open Google Doc Draft',
    admin_feed: 'Admin Feed',
    post_update: 'Post Progress Update',
    update_msg: 'Update Message',
    category_label: 'Category',
    update_type: 'Update Type',
    ward_optional: 'Ward / Area (Optional)',
    publish_update: '📢 Publish Progress Update',
    live_feed: 'Live Updates Feed',
    no_updates: 'No updates from the administrator yet.',
    official_tag: 'Official',
    admin_updates: 'Admin Updates',
    cap_voice_title: 'Voice-First Intake',
    cap_voice_desc: 'Removing literacy barriers by transcribing local dialects and speech instantly via multilingual AI, ensuring every voice is captured accurately.',
    cap_voice_link: 'Learn More →',
    cap_geo_title: 'Geospatial Verification',
    cap_geo_desc: 'Mapping regional needs using precision satellite and open-source data to verify development milestones and infrastructure requirements.',
    cap_geo_link: 'View Map Demo →',
    cap_pred_title: 'Predictive Governance',
    cap_pred_desc: 'Forecasting future infrastructure needs and resource allocation automatically using deep-learning models trained on community feedback.',
    cap_pred_link: 'Explore AI Insights →',
},
  ta: {
    home: 'முகப்பு',
    reports: 'அறிக்கைகள்',
    community: 'சமூக ஊட்டம்',
    profile: 'சுயவிவரம்',
    dashboard: 'டாஷ்போர்டு',
    geospatial: 'புவியியல்',
    insights: 'ஏஐ நுண்ணறிவு',
    audit: 'தணிக்கை பதிவு',
    tagline: 'செயற்கை நுண்ணறிவு அடிப்படையிலான தொகுதி நுண்ணறிவு தளம்',
    citizen_login: 'குடிமகன் உள்நுழைவு',
    admin_login: 'நிர்வாகி உள்நுழைவு',
    citizen_portal_btn: 'குடிமகன் போர்டல் ▷',
    admin_center_btn: 'நிர்வாக மையம் 🛡️',
    capabilities_title: 'உங்கள் தொகுதிக்கான நுண்ணறிவு அடுக்கு',
    capabilities_desc: 'தேவைகளை உடனுக்குடன் கண்டறிந்து தீர்வு காண உதவுகிறது.',
    share_concern: 'உங்கள் கவலையைப் பகிரவும்',
    state: 'மாநிலம்',
    district: 'மாவட்டம்',
    city: 'நகரம்',
    ward_label: 'வார்டு / பகுதி பெயர்',
    category: 'வகை',
    specify_other: 'வேறு வகையைக் குறிப்பிடவும்',
    desc_label: 'விரிவான விளக்கம்',
    voice_typing: 'குரல் தட்டச்சு',
    listening: 'கேட்கிறது...',
    upload_proof: 'புகைப்படம் / வீடியோ ஆதாரம் பதிவேற்றவும்',
    upload_hint: '(ஆதாரங்களை சமர்ப்பிப்பது முன்னுரிமையுடன் கூடிய தீர்வை உறுதி செய்யும்)',
    submit_report: 'புகார் சமர்ப்பி / 𝍢𝍢𝍢𝍢𝍢',
    submitting: 'புகார் பதிவு செய்யப்படுகிறது...',
    call_hotline: 'தானியங்கி அழைப்பு எண்: 1800-JAN-SAATH',
    whatsapp_hotline: 'வாட்ஸ்அப் புகார் எண்: +91 98000 00000',
    submitted: 'புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    submitted_desc: 'உங்கள் புகார் பதிவு செய்யப்பட்டுள்ளது. ஏஐ தளம் இதனை சரிபார்த்து வருகிறது.',
    triage_profile: 'விவர விவரங்கள்:',
    severity: 'தீவிரம்',
    priority_score: 'முன்னுரிமை மதிப்பெண்',
    file_another: 'மற்றொரு புகாரைப் பதிவு செய்ய',
    community_feed: 'சமூக ஊட்டம்',
    feed_description: 'உங்கள் தொகுதியின் நேரடி புகார்கள் - அதிக முன்னுரிமை முதலில்',
    upvotes: 'ஆதரவுகள்',
    comments: 'கருத்துகள்',
    abort: 'கைவிடு',
    aborted_notice: 'இந்தப் புகார் குடிமகனால் திரும்பப் பெறப்பட்டது.',
    anonymous: 'பெயர் தெரியாத குடிமகன்',
    add_comment: 'உங்கள் கருத்தைச் சேர்க்கவும்...',
    active_hotspots: 'புவிசார் நேரடி வரைபடம்',
    map_desc: 'வரைபடத்தில் காண பின்களைக் கிளிக் செய்யவும்.',
    agent_workflow: 'கணினி முகவர் வரைபட பணிப்பாய்வு',
    incidents_directory: 'வார்டு உள்கட்டமைப்பு புகார்கள் பட்டியல்',
    id: 'புகார் எண்',
    status: 'நிலை',
    logged_at: 'பதிவு செய்யப்பட்ட நேரம்',
    profile_rep: 'தொகுதிப் பிரதிநிதி',
    email_addr: 'மின்னஞ்சல் முகவரி',
    phone_num: 'தொலைபேசி எண்',
    age: 'வயது',
    years: 'ஆண்டுகள்',
    default_ward: 'இயல்பு வார்டு',
    city_district: 'நகரம் & மாவட்டம்',
    state_region: 'மாநில பகுதி',
    total_issues: 'மொத்த புகார்கள்',
    resolved: 'தீர்க்கப்பட்டவை',
    avg_resolution: 'சராசரி தீர்வு காலம்',
    satisfaction: 'திருப்தி விகிதம்',
    draft_proposal: 'அரசு வரைவு அறிக்கை',
    command_insight: 'ஏஐ நிர்வாக நுண்ணறிவு',
    urgency_score: 'அவசர மதிப்பெண்',
    affected_pop: 'பாதிக்கப்பட்ட மக்கள்',
    fiscal_estimate: 'நிதி மதிப்பீடு',
    generate_proposal: 'வரைவு அறிக்கையை உருவாக்கு',
    proposal_success: 'கூகுள் டாக்ஸில் வரைவு அறிக்கை உருவாக்கப்பட்டது! புதிய தாவலில் திறக்கவும்.',
    empty_column: 'வெற்றுப் பத்தி',
    logout: 'வெளியேறு',
    call_us: '📞 அழைப்பு',
    call_description: 'உங்கள் புகாரைக் கூறுங்கள் - இணையம் தேவையிணை',
    whatsapp: '💬 வாட்ஸ்அப்',
    whatsapp_description: 'வாட்ஸ்அப்பில் செய்தி அனுப்பவும்',
    upload_photo: '📷 புகைப்படம் பதிவேற்றவும்',
    photo_description: 'பிரச்சனையின் புகைப்படம் எடுக்கவும்',
    text_complaint: '✍️ எழுத்துப் புகார்',
    text_description: 'உங்கள் புகாரை தட்டச்சு செய்யவும்',
    submit: 'சமர்ப்பி',
    done: 'முடிந்தது',
    describe_problem: 'உங்கள் பிரச்சனையை விரிவாக விவரிக்கவும்...',
    enter_ward: 'வார்டு பெயரை உள்ளிடவும் (எ.கா., சின்ஹாட்)',
    photo_hint: 'பிரச்சனையின் தெளிவான புகைப்படத்தை எடுக்கவும்',
    no_complaints: 'இன்னும் புகார்கள் எதுவும் இல்லை. முதன்முதலில் புகார் செய்ய!',
    loading: 'ஏற்றப்படுகிறது',
    priority: 'முன்னுரிமை',
    merged_issue: 'இணைக்கப்பட்ட பிரச்சனை',
    days: 'நாட்கள்',
    summary: 'சுருக்கம்',
      workflow_title: 'Workflow Action Control',
    pass_review: '🔍 Pass for Review',
    allocate_funds: '💰 Allocate Funds',
    resolve_direct: '✅ Resolve Direct',
    resolve_issue: '✅ Resolve Issue',
    resolved_closed: '🎉 Issue is fully resolved & closed.',
    open_google_doc: '🔗 Open Google Doc Draft',
    admin_feed: 'Admin Feed',
    post_update: 'Post Progress Update',
    update_msg: 'Update Message',
    category_label: 'Category',
    update_type: 'Update Type',
    ward_optional: 'Ward / Area (Optional)',
    publish_update: '📢 Publish Progress Update',
    live_feed: 'Live Updates Feed',
    no_updates: 'No updates from the administrator yet.',
    official_tag: 'Official',
    admin_updates: 'Admin Updates',
    cap_voice_title: 'Voice-First Intake',
    cap_voice_desc: 'Removing literacy barriers by transcribing local dialects and speech instantly via multilingual AI, ensuring every voice is captured accurately.',
    cap_voice_link: 'Learn More →',
    cap_geo_title: 'Geospatial Verification',
    cap_geo_desc: 'Mapping regional needs using precision satellite and open-source data to verify development milestones and infrastructure requirements.',
    cap_geo_link: 'View Map Demo →',
    cap_pred_title: 'Predictive Governance',
    cap_pred_desc: 'Forecasting future infrastructure needs and resource allocation automatically using deep-learning models trained on community feedback.',
    cap_pred_link: 'Explore AI Insights →',
},
  te: {
    home: 'హోమ్',
    reports: 'నివేదికలు',
    community: 'కమ్యూనిటీ ఫీడ్',
    profile: 'ప్రొఫైల్',
    dashboard: 'డాష్‌బోర్డ్',
    geospatial: 'జియోస్పేషియల్',
    insights: 'ఏఐ అంతర్దృష్టులు',
    audit: 'ఆడిట్ లాగ్',
    tagline: 'AI-ఆధారిత నియోజకవర్గ ఇంటెలిజెన్స్ ప్లాట్‌ఫాం',
    citizen_login: 'సిటిజన్ లాగిన్',
    admin_login: 'అడ్మిన్ లాగిన్',
    citizen_portal_btn: 'సిటిజన్ పోర్టల్ ▷',
    admin_center_btn: 'అడ్మిన్ కేంద్రం 🛡️',
    capabilities_title: 'మీ నియోజకవర్గం కోసం ఇంటెలిజెన్స్ లేయర్',
    capabilities_desc: 'సమస్యలను త్వరగా గుర్తించి పరిష్కారానికి సమాచారాన్ని అందిస్తుంది.',
    share_concern: 'మీ సమస్యను పంచుకోండి',
    state: 'రాష్ట్రం',
    district: 'జిల్లా',
    city: 'నగరం',
    ward_label: 'వార్డు / ప్రాంతం పేరు',
    category: 'వర్గం',
    specify_other: 'ఇతర వర్గాన్ని పేర్కొనండి',
    desc_label: 'సవివరమైన వివరణ',
    voice_typing: 'వాయిస్ టైపింగ్',
    listening: 'వింటున్నాము...',
    upload_proof: 'ఫోటో / వీడియో ఆధారం అప్‌లోడ్ చేయండి',
    upload_hint: '(మీడియా ఆధారం సమర్పించడం వల్ల త్వరగా పరిష్కరించబడుతుంది)',
    submit_report: 'నివేదిక సమర్పించు / 𝍢𝍢𝍢𝍢𝍢',
    submitting: 'ఫిర్యాదు నమోదు అవుతోంది...',
    call_hotline: 'వాయిస్ హాట్‌లైన్ నంబర్: 1800-JAN-SAATH',
    whatsapp_hotline: 'వాట్సాప్ హాట్‌లైన్ నంబర్: +91 98000 00000',
    submitted: 'ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!',
    submitted_desc: 'మీ ఫిర్యాదు విజయవంతంగా నమోదైంది. ఏఐ సిస్టమ్ పరిశీలిస్తోంది.',
    triage_profile: 'వర్గీకరణ వివరాలు:',
    severity: 'తీవ్రత',
    priority_score: 'ప్రాధాన్యత స్కోరు',
    file_another: 'మరొక ఫిర్యాదు నమోదు చేయండి',
    community_feed: 'కమ్యూనిటీ ఫీడ్',
    feed_description: 'మీ నియోజకవర్గం నుండి ప్రత్యక్ష ఫిర్యాదులు - గరిష్ట ప్రాధాన్యత కలిగినవి మొదట',
    upvotes: 'మద్దతులు',
    comments: 'వ్యాఖ్యలు',
    abort: 'రద్దు చేయి',
    aborted_notice: 'ఈ ఫిర్యాదు పౌరుడిచే రద్దు చేయబడింది.',
    anonymous: 'అజ్ఞాత పౌరుడు',
    add_comment: 'మీ వ్యాఖ్యను చేర్చండి...',
    active_hotspots: 'భౌగోళిక ప్రత్యక్ష హాట్‌స్పాట్లు',
    map_desc: 'వివరాలు చూడండి.',
    agent_workflow: 'కంప్యూటేషనల్ ఏజెంట్ గ్రాఫ్ వర్క్‌ఫ్లో',
    incidents_directory: 'వార్డు మౌలిక సదుపాయాల సమస్యల జాబితా',
    id: 'ఐడి నంబర్',
    status: 'పరిస్థితి',
    logged_at: 'నమోదైన సమయం',
    profile_rep: 'పౌర ప్రతినిధి',
    email_addr: 'ఇమెయిల్ చిరునామా',
    phone_num: 'ఫోన్ నంబర్',
    age: 'వయస్సు',
    years: 'సంవత్సరాలు',
    default_ward: 'డిఫాల్ట్ వార్డు',
    city_district: 'నగరం & జిల్లా',
    state_region: 'రాష్ట్ర ప్రాంతం',
    total_issues: 'మొత్తం ఫిర్యాదులు',
    resolved: 'పరిష్కరించబడినవి',
    avg_resolution: 'సగటు పరిష్కార కాలం',
    satisfaction: 'సంతృప్తి రేటు',
    draft_proposal: 'ప్రభుత్వ ముసాయిదా నివేదిక',
    command_insight: 'ఏఐ అడ్మిన్ అంతర్దूठी',
    urgency_score: 'అత్యవసర స్కోరు',
    affected_pop: 'బాధిత జనాభా',
    fiscal_estimate: 'ఆర్థిక అంచనా',
    generate_proposal: 'ముసాయిదా నివేదికను సృష్టించు',
    proposal_success: 'గూగుల్ డాక్స్‌లో ముసాయిదా నివేదిక సృష్టించబడింది! కొత్త ట్యాబ్‌లో తెరవండి.',
    empty_column: 'ఖాళీ నిలువు వరుస',
    logout: 'లాగౌట్',
    call_us: '📞 కాల్ చేయండి',
    call_description: 'మీ ఫిర్యాదును మాట్లాడండి - ఇంటర్నెట్ అవసరం లేదు',
    whatsapp: '💬 వాట్సాప్',
    whatsapp_description: 'వాట్సాప్‌లో సందేశం పంపండి',
    upload_photo: '📷 ఫోటో అప్‌లోడ్',
    photo_description: 'సమస్య యొక్క ఫోటో తీయండి',
    text_complaint: '✍️ టెక్స్ట్ ఫిర్యాదు',
    text_description: 'మీ ఫిర్యాదును టైప్ చేయండి',
    submit: 'సమర్పించండి',
    done: 'పూర్తయింది',
    describe_problem: 'మీ సమస్యను వివరంగా వివరించండి...',
    enter_ward: 'వార్డు పేరును నమోదు చేయండి (ఉదా., చిన్హాట్)',
    photo_hint: 'సమస్య యొక్క స్పష్టమైన ఫోటో తీయండి',
    no_complaints: 'ఇంకా ఎలాంటి ఫిర్యాదులు లేవు. మొదట రిపోర్ట్ చేయండి!',
    loading: 'లోడ్ అవుతోంది',
    priority: 'ప్రాధాన్యత',
    merged_issue: 'విలీన సమస్య',
    days: 'రోజులు',
    summary: 'సారాంశం',
      workflow_title: 'Workflow Action Control',
    pass_review: '🔍 Pass for Review',
    allocate_funds: '💰 Allocate Funds',
    resolve_direct: '✅ Resolve Direct',
    resolve_issue: '✅ Resolve Issue',
    resolved_closed: '🎉 Issue is fully resolved & closed.',
    open_google_doc: '🔗 Open Google Doc Draft',
    admin_feed: 'Admin Feed',
    post_update: 'Post Progress Update',
    update_msg: 'Update Message',
    category_label: 'Category',
    update_type: 'Update Type',
    ward_optional: 'Ward / Area (Optional)',
    publish_update: '📢 Publish Progress Update',
    live_feed: 'Live Updates Feed',
    no_updates: 'No updates from the administrator yet.',
    official_tag: 'Official',
    admin_updates: 'Admin Updates',
    cap_voice_title: 'Voice-First Intake',
    cap_voice_desc: 'Removing literacy barriers by transcribing local dialects and speech instantly via multilingual AI, ensuring every voice is captured accurately.',
    cap_voice_link: 'Learn More →',
    cap_geo_title: 'Geospatial Verification',
    cap_geo_desc: 'Mapping regional needs using precision satellite and open-source data to verify development milestones and infrastructure requirements.',
    cap_geo_link: 'View Map Demo →',
    cap_pred_title: 'Predictive Governance',
    cap_pred_desc: 'Forecasting future infrastructure needs and resource allocation automatically using deep-learning models trained on community feedback.',
    cap_pred_link: 'Explore AI Insights →',
},
  mr: {
    home: 'मुख्यपृष्ठ',
    reports: 'अहवाल',
    community: 'कम्युनिटी फीड',
    profile: 'प्रोफाइल',
    dashboard: 'डॅशबोर्ड',
    geospatial: 'भौगोलिक',
    insights: 'एआय अंतर्दृष्टी',
    audit: 'ऑडिट लॉग',
    tagline: 'एआय-संचालित मतदारसंघ बुद्धिमत्ता मंच',
    citizen_login: 'नागरिक लॉगिन',
    admin_login: 'प्रशासक लॉगिन',
    citizen_portal_btn: 'नागरिक पोर्टल ▷',
    admin_center_btn: 'प्रशासक केंद्र 🛡️',
    capabilities_title: 'तुमच्या मतदारसंघासाठी बुद्धिमत्ता स्तर',
    capabilities_desc: 'पारदर्शकता वाढवण्यासाठी एआय तंत्रज्ञानाचा वापर.',
    share_concern: 'तुमची समस्या नोंदवा',
    state: 'राज्य',
    district: 'जिल्हा',
    city: 'शहर',
    ward_label: 'वॉर्ड / परिसराचे नाव',
    category: 'वर्ग',
    specify_other: 'इतर वर्ग नमूद करा',
    desc_label: 'सविस्तर वर्णन',
    voice_typing: 'आवाज टायपिंग',
    listening: 'ऐकत आहे...',
    upload_proof: 'फोटो / व्हिडिओ पुरावा अपलोड करा',
    upload_hint: '(पुराव्यासह तक्रार नोंदविल्यास त्वरित निवारण सुनिश्चित केले जाते)',
    submit_report: 'तक्रार नोंदवा / 𝍢𝍢𝍢𝍢𝍢',
    submitting: 'तक्रार नोंदवली जात आहे...',
    call_hotline: 'कॉल करा व्हॉइस हेल्पलाईन: 1800-JAN-SAATH',
    whatsapp_hotline: 'व्हॉट्सॲप तक्रार: +91 98000 00000',
    submitted: 'तक्रार यशस्वीरित्या नोंदवली गेली!',
    submitted_desc: 'तुमची तक्रार यशस्वीरीत्या नोंदवली गेली आहे. एआय तपासणी सुरू आहे.',
    triage_profile: 'तक्रार वर्गीकरण तपशील:',
    severity: 'गंभीरता',
    priority_score: 'प्राधान्य गुणसंख्या',
    file_another: 'नवीन तक्रार नोंदवा',
    community_feed: 'कम्युनिटी फीड',
    feed_description: 'तुमच्या मतदारसंघातील थेट तक्रारी - उच्च प्राधान्य आधी',
    upvotes: 'समर्थन',
    comments: 'प्रतिक्रिया',
    abort: 'रद्द करा',
    aborted_notice: 'ही तक्रार संबंधित नागरिकाने रद्द/मागे घेतली आहे.',
    anonymous: 'अनामिक नागरिक',
    add_comment: 'तुमची प्रतिक्रिया जोडा...',
    active_hotspots: 'भौगोलिक सक्रिय हॉटस्पॉट',
    map_desc: 'नकाशावरील स्थान पाहण्यासाठी पिनवर क्लिक करा.',
    agent_workflow: 'कम्प्युटेशनल एजंट ग्राफ कार्यप्रवाह',
    incidents_directory: 'वॉर्ड पायाभूत सुविधा तक्रारी यादी',
    id: 'तक्रार क्रमांक',
    status: 'स्थिती',
    logged_at: 'नोंदणीची वेळ',
    profile_rep: 'नागरिक प्रतिनिधी',
    email_addr: 'ईमेल पत्ता',
    phone_num: 'फोन नंबर',
    age: 'वय',
    years: 'वर्षे',
    default_ward: 'डिफॉल्ट वॉर्ड',
    city_district: 'शहर आणि जिल्हा',
    state_region: 'राज्य प्रदेश',
    total_issues: 'एकूण तक्रारी',
    resolved: 'निवारण झालेल्या',
    avg_resolution: 'सरासरी निवारण वेळ',
    satisfaction: 'समाधान',
    draft_proposal: 'सरकारी प्रस्ताव मसुदा',
    command_insight: 'एआय प्रशासकीय अंतर्दृष्टी',
    urgency_score: 'अति-आवश्यकता गुणसंख्या',
    affected_pop: 'बाधित लोकसंख्या',
    fiscal_estimate: 'आर्थिक अंदाज',
    generate_proposal: 'सरकारी प्रस्ताव तयार करा',
    proposal_success: 'गूगल डॉक्समध्ये प्रस्ताव तयार केला! नवीन टॅबमध्ये उघडला.',
    empty_column: 'रिकामी जागा',
    logout: 'लॉगआउट',
    call_us: '📞 कॉल करा',
    call_description: 'तुमची तक्रार बोला - इंटरनेटची गरज नाही',
    whatsapp: '💬 व्हॉट्सॲप',
    whatsapp_description: 'व्हॉट्सॲपवर संदेश पाठवा',
    upload_photo: '📷 फोटो अपलोड करा',
    photo_description: 'समस्येचा फोटो घ्या',
    text_complaint: '✍️ लेखी तक्रार',
    text_description: 'तक्रार टाईप करा',
    submit: 'जमा करा',
    done: 'पूर्ण झाले',
    describe_problem: 'तुमच्या समस्येचे सविस्तर वर्णन करा...',
    enter_ward: 'वॉर्डचे नाव प्रविष्ट करा (उदा. चिनहट)',
    photo_hint: 'समस्येचा स्पष्ट फोटो घ्या',
    no_complaints: 'अद्याप एकही तक्रार नाही। पहिली तक्रार नोंदवा!',
    loading: 'लोड होत आहे',
    priority: 'प्राधान्य',
    merged_issue: 'एकत्रित मुद्दा',
    days: 'दिवस',
    summary: 'सारांश',
      workflow_title: 'Workflow Action Control',
    pass_review: '🔍 Pass for Review',
    allocate_funds: '💰 Allocate Funds',
    resolve_direct: '✅ Resolve Direct',
    resolve_issue: '✅ Resolve Issue',
    resolved_closed: '🎉 Issue is fully resolved & closed.',
    open_google_doc: '🔗 Open Google Doc Draft',
    admin_feed: 'Admin Feed',
    post_update: 'Post Progress Update',
    update_msg: 'Update Message',
    category_label: 'Category',
    update_type: 'Update Type',
    ward_optional: 'Ward / Area (Optional)',
    publish_update: '📢 Publish Progress Update',
    live_feed: 'Live Updates Feed',
    no_updates: 'No updates from the administrator yet.',
    official_tag: 'Official',
    admin_updates: 'Admin Updates',
    cap_voice_title: 'Voice-First Intake',
    cap_voice_desc: 'Removing literacy barriers by transcribing local dialects and speech instantly via multilingual AI, ensuring every voice is captured accurately.',
    cap_voice_link: 'Learn More →',
    cap_geo_title: 'Geospatial Verification',
    cap_geo_desc: 'Mapping regional needs using precision satellite and open-source data to verify development milestones and infrastructure requirements.',
    cap_geo_link: 'View Map Demo →',
    cap_pred_title: 'Predictive Governance',
    cap_pred_desc: 'Forecasting future infrastructure needs and resource allocation automatically using deep-learning models trained on community feedback.',
    cap_pred_link: 'Explore AI Insights →',
}
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};